//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODOANHTHU
    {
        public string MaBCDT { get; set; }
        public string ThangBaoCao { get; set; }
        public string NamBaoCao { get; set; }
        public string SoBenhNhan { get; set; }
        public string TongDoanhThu { get; set; }
    }
}
