//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAMBENH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAMBENH()
        {
            this.QLBENHNHANs = new HashSet<QLBENHNHAN>();
        }
    
        public string MaPhieuKham { get; set; }
        public string TrieuChung { get; set; }
        public string LoaiBenh { get; set; }
        public string MaThuoc { get; set; }
        public string SoLuongDung { get; set; }
        public Nullable<int> STTKham { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string GioKham { get; set; }
        public string MaHD { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual THUOC THUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLBENHNHAN> QLBENHNHANs { get; set; }
    }
}
