//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLLich
    {
        public string MaLich { get; set; }
        public string MaBN { get; set; }
        public Nullable<System.DateTime> NgayDatLich { get; set; }
        public string GioDatLich { get; set; }
    
        public virtual QLBENHNHAN QLBENHNHAN { get; set; }
    }
}
