//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPMT
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.PHIEUKHAMBENHs = new HashSet<PHIEUKHAMBENH>();
        }
    
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string CachDung { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> GiaThuoc { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<int> SoLuongTrongKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKHAMBENH> PHIEUKHAMBENHs { get; set; }
    }
}
